Add PIS script
teaconmc/DataPack pull request #168
Opened 2023-08-25 15:39 UTC by zbx1425

**版权声明：我同意在我的 Pull Request 合并成功后，Pull Request 中的内容视作进入公有领域（Public Domain）。**

2023-08-27 06:07 UTC, 3TUSK commented
如果你还需要继续更新，可考虑先将该 PR 状态改为 Draft，待完成后再改回 Open。

2023-08-27 06:15 UTC, zbx1425 commented
现在就可以合并；还需要更新我会再开 PR

2023-08-27 21:07 UTC, 3TUSK requested changes

2023-08-27 21:07 UTC, 3TUSK commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
Noto Sans CJK 使用的 SIL 开源字体授权不允许我们在分发时使用其他授权，必须保持 SIL 开源字体授权。

给我一点时间我想想该怎么做。

2023-08-28 04:16 UTC, zbx1425 commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
我把 Noto Sans CJK 嵌入到 mod 里好了，对于将来的资源包作者也会更方便。
不过这就应该会超 10MB，您看可不可以给加一下豁免。

2023-08-30 15:25 UTC, zbx1425 commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
移除了字体，现在可以合并了

2023-09-04 05:25 UTC, 3TUSK commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
> 移除了字体，现在可以合并了

那字体打算加到哪里？Mod 本体吗？

2023-09-04 05:45 UTC, zbx1425 commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
> 那字体打算加到哪里？Mod 本体吗？

https://github.com/zbx1425/Minecraft-Transit-Railway/commit/b1b221b058483dfb3fc5cf4942b06e84ec842052

这个我稍后也会和上游那位作者那边提，因为那边既然本来就已经嵌入了 Noto-Serif-CJK 和 Noto-Sans，把 Noto-Sans 换成 Noto-Sans-CJK 也不算不合理

2023-09-04 06:25 UTC, 3TUSK commented on 2023/vanilla-assets/src/main/resources/assets/mtr/font/noto-sans-cjk-sc-medium.otf
了解。

2023-09-04 06:25 UTC, merged