符·道 附属数据包
teaconmc/DataPack pull request #2
Opened 2021-07-24 15:55 UTC by Gu-ZT

2021-07-24 21:49 UTC, ustc-zzzz requested changes
* 除去必要的 function tag 外，其他 tag（方块物品实体流体）看起来和原版数据包没有差别，请去除。
* mcfunction 方面……不要在 `minecraft` 域下加 mcfunction，尤其是 `minecraft:init` 这种标识符……
* `math` 这个数据包大量记分板变量没加前缀……算了这个估计改不掉了，就这样，我回头看一下都有哪些。

2021-07-25 02:36 UTC, MalayPrime commented
"如何评价用java写的模组却需要三万行数学库"

2021-07-25 04:48 UTC, Gu-ZT commented
为什么我会写一串和原版一模一样的tag，因为考虑到某种特殊情况——当原版数据包被禁用，删了的话，禁原版数据包，游戏会进不去，不过没有禁用原版数据包删了也行。

2021-07-25 04:48 UTC, Gu-ZT commented
> * 除去必要的 function tag 外，其他 tag（方块物品实体流体）看起来和原版数据包没有差别，请去除。
> * mcfunction 方面……不要在 `minecraft` 域下加 mcfunction，尤其是 `minecraft:init` 这种标识符……
> * `math` 这个数据包大量记分板变量没加前缀，记分板标签同理……算了这个估计改不掉了，我回头看一下都有哪些好了。

为什么我会写一串和原版一模一样的tag，因为考虑到某种特殊情况——当原版数据包被禁用，删了的话，禁原版数据包，游戏会进不去，不过没有禁用原版数据包删了也行。

2021-07-25 07:42 UTC, ustc-zzzz approved these changes

2021-07-25 07:42 UTC, merged